unique_ids:
  forms:
    homepage: WOQ7BXCIRYGXZSN4N6KNQ7COCKISXGL3
    homepage.RowTemplate1: YGHNPRBPTGWQBDFKIG2YAFWJJJNSYRGU
    homepage.form: 3Z6PRYGLN5IOTYKKBATXZVOJ7DL324ZM
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: J3PMZ3GWQD2E4UGZN65KJUJ2K7BOSEV7
    theme.css: ESM6NYB3NT2DLWIF5FPECD7PCYHTHAM5
